# Generated by Django 4.2.4 on 2023-09-07 07:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='movie_image')),
                ('trailer', models.FileField(max_length=500, upload_to=None)),
                ('category', models.CharField(choices=[('Mlayalam', 'Malayalam'), ('Tamil', 'Tamil'), ('Hindi', 'Hindi')], default='Malayalam', max_length=200)),
                ('description', models.CharField(max_length=500, null=True)),
                ('rating', models.IntegerField(default='5')),
                ('cast', models.ImageField(null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Theaters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('show', models.TimeField()),
                ('adress', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.IntegerField()),
                ('show', models.TimeField()),
                ('status', models.CharField(choices=[('Booking Confirmed', 'Booking Confirmed'), ('Cancelled', 'Cancelled')], default='Booking confirmed', max_length=100)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.movies')),
                ('theater', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='theaterbook', to='customer.theaters')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
