# Generated by Django 4.2.4 on 2023-09-07 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movies',
            old_name='cast',
            new_name='cast2',
        ),
        migrations.AddField(
            model_name='movies',
            name='cast1',
            field=models.ImageField(null=True, upload_to='movie_image'),
        ),
        migrations.AddField(
            model_name='movies',
            name='cast3',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='movies',
            name='cast4',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='movies',
            name='cast5',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='movies',
            name='category',
            field=models.CharField(choices=[('Malayalam', 'Malayalam'), ('Tamil', 'Tamil'), ('Hindi', 'Hindi')], default='Malayalam', max_length=200),
        ),
    ]
