# Generated by Django 4.2.4 on 2023-09-16 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_rename_cast_movies_cast2_movies_cast1_movies_cast3_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='rating',
            field=models.FloatField(default='5'),
        ),
    ]
