# Generated by Django 4.2.4 on 2023-09-16 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_alter_movies_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='seat',
            field=models.IntegerField(null=True),
        ),
    ]
