# Generated by Django 4.2.4 on 2023-09-17 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_books_seat'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
